import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import BottomNav from "@/components/BottomNav";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900 min-h-screen pb-16`}
      >
        {/* Mobile viewport constraint for web preview */}
        <div className="max-w-md mx-auto min-h-screen bg-white relative shadow-2xl overflow-x-hidden">
          <main className="min-h-[calc(100vh-4rem)]">
            {children}
          </main>
          <BottomNav />
        </div>
      </body>
    </html>
  );
}
